version: "3"

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    hostname: pihole
    networks:
      pih_network:
        ipv4_address: 192.168.1.149   #pihole address
    environment:
      TZ: 'Australia/Brisbane'     #Change to your timezone
      WEBPASSWORD: 'password'   #Password for pihole, used on container creation.
      PIHOLE_DNS_: 127.0.0.1#5335
    ports:
      - "443:443/tcp"
      - "53:53/tcp"
      - "67:67/udp" # Only required if you are using Pi-hole as your DHCP server
      - "53:53/udp"
      - "80:80/tcp"
    volumes:
      - "./etc/pihole:/etc/pihole"
      - "./etc/dnsmasq.d:/etc/dnsmasq.d"
    cap_add:
      - NET_ADMIN # Required if you are using Pi-hole as your DHCP server, else not needed
    restart: "unless-stopped"

networks:
  pih_network:
    driver: macvlan
    driver_opts:
      parent: eth0  
    ipam:
      config:
        - subnet: 192.168.1.0/24     # Your network subnet
          gateway: 192.168.1.1       # Your network gateway
          ip_range: 192.168.1.149/32  # ip for pihole container

