version: "3"

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    hostname: pihole
    networks:
      macvlan_network:
        ipv4_address: 192.168.1.149
    environment:
      - TZ=Australia/Brisbane
      - FTLCONF_webserver_api_password=pipassword
    ports:
      - "443:443/tcp"
      - "53:53/tcp"
      - "67:67/udp"
      - "53:53/udp"
      - "80:80/tcp"
    volumes:
      - "./etc/pihole:/etc/pihole"
    cap_add:
      - NET_ADMIN
    restart: unless-stopped

networks:
  macvlan_network:
    driver: macvlan
    driver_opts:
      parent: enp4s0
    ipam:
      config:
        - subnet: 192.168.1.0/24
          gateway: 192.168.1.1
          ip_range: 192.168.1.149/32

