version: "3.7"

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    hostname: pihole
    networks:
      ipvlan_base:
        ipv4_address: 10.9.8.149
    environment:
      TZ: 'Australia/Brisbane'
      WEBPASSWORD: 'password'
    ports:
      - "443:443/tcp"
      - "53:53/tcp"
      - "67:67/udp"
      - "53:53/udp"
      - "80:80/tcp"
    volumes:
      - "./etc/pihole:/etc/pihole"
      - "./etc/dnsmasq.d:/etc/dnsmasq.d"
    cap_add:
      - NET_ADMIN
    restart: unless-stopped

networks:
  ipvlan_base:
    external: true

