version: '3'

services:
  pihole:
    container_name: pihole
    image: pihole/pihole:latest
    networks:
      pihole_network:
        ipv4_address: 192.168.1.149 # update with the desired IP address
    ports:
      - "53:53/tcp"
      - "53:53/udp"
      - "67:67/udp" # Only required if you are using Pi-hole as your DHCP server
      - "80:80/tcp"
    environment:
      TZ: 'Australia/Brisbane' # update according to your timezone
      WEBPASSWORD: 'password' # update password
      PIHOLE_DNS_: 127.0.0.1#5335
    volumes:
      - './etc-pihole:/etc/pihole' # update
      - './etc-dnsmasq.d:/etc/dnsmasq.d' # update
    cap_add:
      - NET_ADMIN
    restart: unless-stopped

networks:
  pihole_network:
    driver: bridge

